### PR TITLE
Fix for the leg_detector opencv3 bug

### PR DESCRIPTION
**Pull request by kdhansen**
This is a fix for #44 and in turn #47. I have changed the CvMat C-style calls to the corresponding C++style of opencv3. Also the fuzzy probability call predict_prob no longer exists, so I implemented a replacement. I have not done a comparison test with Indigo, as I have no working Indigo-installation, but it looks good to me on 16.04+Kinetic.

### CODE REVIEW

**Comment by kdhansen** [comment]
It seems I cannot make Travis build. Can someone with superior knowledge take over, please?

**Comment by kdhansen** [comment]
Oh! I get it... Travis does not run Xenial (16.04) and Kinetic does not support Trusty (14.04). So we cannot test Kinetic code on Travis...

**Comment by 130s** [comment]
Sorry for the delay. https://github.com/wg-perception/people/pull/49 is finally ready for the review. Once it's merged you may rebase your PR to run test against.

**Comment by kdhansen** [comment]
@130s I tried rebasing on your k/update_travis branch, but for some reason I get the error with the haarcascade file in Travis:
"Cascade file /opt/ros/kinetic/share/OpenCV-3.1.0-dev/haarcascades/haarcascade_frontalface_alt.xml doesn't exist."

On another note, I totally screwed something up when rebasing, that is why I closed the pull request. I will open it when #49 has been merged.

**Comment by kdhansen** [comment]
Ok, so OpenCV was just updated to 3.2.0. I tried changing the hardcoded location, now I get a pass on Travis.

**Pull request closed without merging**
