### PR TITLE
2d visualization topic

### PR DESCRIPTION
**Pull request by Cakem1x**
Hi there,

I just added code for publishing another ROS-topic (/face_detection/faces_video) which displays the detected faces just like in the opencv highgui window.

Also, should there be no subscriber to the ROS-topic then no operations for the visualization will be performed.

### CODE REVIEW

**Comment by linas** [comment]
Any reason this pull request hasn't been merged yet?

**Comment by dlaz** [comment]
This pr needs to be rebased to d1059893b60d5b863bd7ddd14503428545d19c5a.

**Comment by Cakem1x** [comment]
Wrote a new commit on basis of the changed codestyle, so I'm closing this pr. Will open a new one when I had the chance to test my code.

**Comment by dlaz** [comment]
Thanks! Again, sorry about having to do this so many times.

**Comment by Cakem1x** [comment]
No problem, I'm quite thankful that this is an open-source project,
otherwise I wouldn't be able to use it...

Dan Lazewatsky notifications@github.com schrieb am Wed Dec 24 2014 at
11:11:06 PM:

**Pull request closed without merging**
